MangAdventure/urls.py
"""The root URLconf."""

from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.views.decorators.cache import cache_control

from reader import feeds

from .sitemaps import MiscSitemap
from .views import contribute, index, manifest, opensearch, robots, search

_sitemaps = {'sitemaps': {'main': MiscSitemap}}

_sitemap = cache_control(max_age=86400, must_revalidate=True)(sitemap)

#: The main URL patterns.
urlpatterns = [
    path('', index, name='index'),
    path('', include('config.urls')),
    path('search/', search, name='search'),
    path('admin-panel/', admin.site.urls),
    path('reader/', include('reader.urls')),
    path('api/', include('api.urls')),
    path('groups/', include('groups.urls')),
    path('user/', include('users.urls')),
    path('opensearch.xml', opensearch, name='opensearch'),
    path('contribute.json', contribute, name='contribute'),
    path('manifest.webmanifest', manifest, name='manifest'),
    path('robots.txt', robots, name='robots'),
    path('releases.atom', feeds.ReleasesAtom(), name='releases.atom'),
    path('releases.rss', feeds.ReleasesRSS(), name='releases.rss'),
    path('library.atom', feeds.LibraryAtom(), name='library.atom'),
    path('library.rss', feeds.LibraryAtom(), name='library.rss'),
    path('sitemap.xml', _sitemap, _sitemaps, name='sitemap.xml'),
]


#: See :func:`MangAdventure.views.handler400`.
handler400 = 'MangAdventure.views.handler400'

#: See :func:`MangAdventure.views.handler403`.
handler403 = 'MangAdventure.views.handler403'

#: See :func:`MangAdventure.views.handler404`.
handler404 = 'MangAdventure.views.handler404'

#: See :func:`MangAdventure.views.handler500`.
handler500 = 'MangAdventure.views.handler500'

__all__ = [
    'urlpatterns', 'handler400',
    'handler403', 'handler404', 'handler500',
]

api/urls.py
"""The main URLconf of the api app."""

from django.urls import include, path

#: The URL namespace of the API app.
app_name = 'api'

#: The main URL patterns of the API app.
urlpatterns = [
    path('v1/', include('api.v1.urls')),
    path('v2/', include('api.v2.urls')),
]

__all__ = ['urlpatterns']

reader/urls.py
"""The URLconf of the reader app."""

from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from django.urls import path, register_converter
from django.views.decorators.cache import cache_control

from MangAdventure.converters import FloatConverter

from . import feeds, sitemaps, views

register_converter(FloatConverter, 'float')

#: The URL namespace of the reader app.
app_name = 'reader'

_slug = '<slug:slug>/'
_chapter = f'{_slug}<int:vol>/<float:num>/'
_page = f'{_chapter}<int:page>/'

_sitemaps = {
    'template_name': 'image-sitemap.xml',
    'sitemaps': {
        'series': sitemaps.SeriesSitemap,
        'chapters': sitemaps.ChapterSitemap
    }
}

_sitemap = cache_control(max_age=86400, must_revalidate=True)(sitemap)

#: The URL namespace of the reader app.
urlpatterns = [
    path('', views.directory, name='directory'),
    path(_slug, views.series, name='series'),
    path(_chapter, views.chapter_redirect, name='chapter'),
    path(_page, views.chapter_page, name='page'),
    path(f'{_slug[:-1]}.atom', feeds.ReleasesAtom(), name='series.atom'),
    path(f'{_slug[:-1]}.rss', feeds.ReleasesRSS(), name='series.rss'),
    path('<section>-sitemap.xml', _sitemap, _sitemaps, name='sitemap.xml'),
]

if settings.CONFIG['ALLOW_DLS']:
    urlpatterns.append(
        path(f'{_chapter[:-1]}.cbz', views.chapter_download, name='cbz')
    )

__all__ = ['app_name', 'urlpatterns']

reader/models.py
"""
Database models for the reader app.

.. admonition:: TODO
   :class: warning

   Support multiple languages.
"""

from __future__ import annotations

from hashlib import blake2b
from importlib.util import find_spec
from io import BytesIO
from logging import getLogger
from os import path, remove
from pathlib import PurePath
from shutil import rmtree
from threading import Lock, Thread
from typing import Any
from xml.etree import ElementTree as ET
from zipfile import BadZipfile, ZipFile

from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import (
    GenericForeignKey, GenericRelation
)
from django.contrib.contenttypes.models import ContentType
from django.core.cache import cache
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from django.db import models
from django.db.models.expressions import F
from django.db.models.query_utils import Q
from django.urls import reverse
from django.utils.functional import cached_property
from django.utils.text import slugify
from django.utils.timezone import now

from PIL import Image

from MangAdventure import __version__ as VERSION, storage, utils, validators

from groups.models import Group

if find_spec('sentry_sdk'):  # pragma: no cover
    from sentry_sdk import capture_exception
else:
    def capture_exception(_): pass  # noqa: E704

_update_lock = Lock()
_logger = getLogger('django.db.models')


def _cover_uploader(obj: Series, name: str) -> str:
    name = f'cover.{name.split(".")[-1]}'
    name = str(obj.get_directory() / name)
    if path.exists(name):  # pragma: no cover
        remove(name)
    return name


class _NonZeroIntegerField(models.PositiveSmallIntegerField):
    default_validators = (MinValueValidator(1),)

    def formfield(self, **kwargs):  # pragma: no cover
        # HACK: bypass parent to set min_value to 1
        return super(
            models.PositiveSmallIntegerField, self
        ).formfield(min_value=1, **kwargs)


class AliasManager(models.Manager):
    """A :class:`~django.db.models.Manager` for aliases."""

    def names(self) -> list[str]:
        """
        Get the names of the aliases.

        :return: The values of the ``alias`` field.
        """
        qs = self.get_queryset().order_by('name')
        return list(qs.values_list('name', flat=True))


class Alias(models.Model):
    """A generic alias :class:`~django.db.models.Model`."""
    name = models.CharField(
        blank=True, max_length=255, db_index=True, verbose_name='alias'
    )
    object_id = models.PositiveIntegerField()
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    content_object = GenericForeignKey('content_type', 'object_id')

    objects = AliasManager()

    class Meta:
        verbose_name_plural = 'aliases'
        constraints = (
            models.UniqueConstraint(
                fields=('name', 'content_type', 'object_id'),
                name='unique_alias_content_object'
            ),
        )

    def __str__(self) -> str:
        """Return the alias of the instance."""
        return self.name or ''


class Author(models.Model):
    """A model representing an author."""
    #: The name of the author.
    name = models.CharField(
        max_length=100, db_index=True,
        help_text="The author's full name."
    )
    #: The aliases of the author.
    aliases = GenericRelation(
        to=Alias, blank=True, related_query_name='main'
    )

    def __str__(self) -> str:
        """
        Return a string representing the object.

        :return: The name of the author.
        """
        return self.name


class Artist(models.Model):
    """A model representing an artist."""
    #: The name of the artist.
    name = models.CharField(
        max_length=100, db_index=True,
        help_text="The artist's full name."
    )
    #: The aliases of the artist.
    aliases = GenericRelation(
        to=Alias, blank=True, related_query_name='main'
    )

    def __str__(self) -> str:
        """
        Return a string representing the object.

        :return: The name of the artist.
        """
        return self.name


class Category(models.Model):
    """A model representing a category."""
    #: The category's ID.
    id = models.CharField(
        primary_key=True, max_length=25, auto_created=True
    )
    #: The unique name of the category.
    name = models.CharField(
        unique=True, help_text=(
            'The name of the category. Must be '
            'unique and cannot be changed once set.'
        ), max_length=25
    )
    #: The description of the category.
    description = models.TextField(help_text='A description for the category.')

    class Meta:
        verbose_name_plural = 'categories'
        ordering = ('id',)

    def save(self, *args, **kwargs):
        """Save the current instance."""
        if not self.id:
            self.id = self.name.lower()
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        """
        Return a string representing the object.

        :return: The name of the category.
        """
        return self.name


class Status(models.TextChoices):
    """The possible :attr:`Series.status` values."""
    ONGOING = 'ongoing', 'Ongoing'
    COMPLETED = 'completed', 'Completed'
    HIATUS = 'hiatus', 'On Hiatus'
    CANCELED = 'canceled', 'Canceled'


class Kind(models.TextChoices):
    """The possible :attr:`Series.kind` values."""
    MANGA = 'manga', 'Manga'
    COMIC = 'comic', 'Comic'
    WEBTOON = 'webtoon', 'Webtoon'
    # TODO: support novels
    # NOVEL = 'novel', 'Novel'


class Rating(models.TextChoices):
    """The possible :attr:`Series.rating` values."""
    SAFE = 'safe', 'Safe'
    SUGGESTIVE = 'suggestive', 'Suggestive'
    EXPLICIT = 'explicit', 'Explicit'


class Series(models.Model):
    """A model representing a series."""
    #: The title of the series.
    title = models.CharField(
        max_length=250, db_index=True, help_text='The title of the series.'
    )
    #: The unique slug of the series.
    slug = models.SlugField(
        blank=True, unique=True, verbose_name='Custom slug',
        help_text='The unique slug of the series. Will be used in the URL.'
    )
    #: The description of the series.
    description = models.TextField(
        blank=True, help_text='The description of the series.'
    )
    #: The cover image of the series.
    cover = models.ImageField(
        help_text=(
            'Upload a cover image for the series.'
            ' Its size must not exceed 2 MBs.'
        ), upload_to=_cover_uploader,
        validators=(validators.FileSizeValidator(2),),
        storage=storage.CDNStorage((300, 300))
    )
    #: The authors of the series.
    authors = models.ManyToManyField(Author, blank=True)
    #: The artists of the series.
    artists = models.ManyToManyField(Artist, blank=True)
    #: The categories of the series.
    categories = models.ManyToManyField(Category, blank=True)
    #: The publication status of the series.
    status = models.CharField(
        blank=False, max_length=10,
        choices=Status, default=Status.ONGOING,
        help_text='The publication status of the series.'
    )
    #: The series kind (Manga/Comic/Webtoon/Novel).
    kind = models.CharField(
        blank=False, max_length=8,
        choices=Kind, default=Kind.MANGA,
        help_text='Determines the page layout.'
    )
    #: The content rating of the series.
    rating = models.CharField(
        blank=False, max_length=11,
        choices=Rating, default=Rating.SAFE,
        help_text='The content rating.'
    )
    #: The licensing status of the series.
    licensed = models.BooleanField(
        default=False, help_text='Is the series licensed?'
    )
    #: The date the series was created.
    created = models.DateTimeField(auto_now_add=True)
    #: The modification date of the series.
    modified = models.DateTimeField(auto_now=True, db_index=True)
    #: The chapter name format of the series.
    format = models.CharField(
        default='Vol. {volume}, Ch. {number}: {title}',
        max_length=100, verbose_name='chapter name format',
        help_text='The format used to render the chapter names.'
    )
    #: The aliases of the series.
    aliases = GenericRelation(
        to=Alias, blank=True, related_query_name='alias'
    )
    #: The person who manages this series.
    manager = models.ForeignKey(
        User, editable=True, blank=False, null=True,
        help_text='The person who manages this series.',
        on_delete=models.SET_NULL, limit_choices_to=(
            Q(is_superuser=True) | Q(groups__name='Scanlator')
        )
    )

    class Meta:
        verbose_name_plural = 'series'
        get_latest_by = 'modified'

    def get_absolute_url(self) -> str:
        """
        Get the absolute URL of the object.

        :return: The URL of :func:`reader.views.series`.
        """
        return reverse('reader:series', args=(self.slug,))

    def get_directory(self) -> PurePath:
        """
        Get the storage directory of the object.

        :return: A path relative to
                 :const:`~MangAdventure.settings.MEDIA_ROOT`.
        """
        return PurePath('series', self.slug)

    @cached_property
    def sitemap_images(self) -> list[str]:
        """
        Get the list of images used in the sitemap.

        :return: A list containing the cover.
        """
        return [self.cover.url] if self.cover else []

    def save(self, *args, **kwargs):
        """Save the current instance."""
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        """
        Return a string representing the object.

        :return: The title of the series.
        """
        return self.title


class Chapter(models.Model):
    """A model representing a chapter."""

reader/templates/chapter.html
{% extends 'layout.html' %}
{% load static custom_tags %}
{% block robots %}
  <meta name="robots" content="nosnippet">
{% endblock %}
{% block keywords %}
  <meta name="keywords" content="{{ tags }}">
{% endblock %}
{% block image %}
  <meta name="twitter:card" content="summary">
  {% with cover=PAGE_URL|urljoin:curr_chapter.series.cover.url %}
    <meta name="twitter:image" content="{{ cover }}">
    <meta property="og:image" content="{{ cover }}">
    <meta name="twitter:image:alt" content="Series Cover">
    <meta property="og:image:alt" content="Series Cover">
  {% endwith %}
{% endblock %}
{% block description %}
  <meta property="og:description" content="{{ curr_chapter }}">
  <meta name="description" content="{{ curr_chapter }}">
{% endblock %}
{% block stylesheets %}
  {{ block.super }}
  <link href="{% static 'COMPILED/styles/chapter.css' %}"
        rel="stylesheet preload" type="text/css" as="style">
{% endblock %}
{% block head_extras %}
  {% for page in prefetch %}
    <link href="{{ page.image.url }}" rel="prefetch" as="image">
  {% endfor %}
{% endblock %}
{% block title %}
  <meta name="title" content="{{ curr_chapter.title }}">
  {% with title=curr_chapter.series.title|add:' ~ '|add:config.NAME %}
    <meta property="og:title" content="{{ title }}">
  {% endwith %}
  <title>{{ curr_chapter.title }} &middot; {{ config.NAME }}</title>
{% endblock %}
{% block content %}
  {% with vol=curr_chapter.volume num=curr_chapter.number %}
    <h1>
      <a href="{{ curr_chapter.series.get_absolute_url }}">
        {{ curr_chapter.series.title }}
      </a><br>{% if vol %}V{{ vol }} / {% endif %}C{{ num|stringformat:'g' }}
    </h1>
  {% endwith %}
  <div id="chapter">
    <section id="dropdowns" class="no-display">
      <div class="dropdown chapter-list main-bg" aria-haspopup="true">
        <span class="dropdown-title alter-fg">
          <i class="mi mi-down"></i>Chapters
        </span>
        <a href="#" title="{{ curr_chapter.title }}" class="faux-link">
          <i class="mi mi-down"></i>
          <span{% if curr_chapter.final %} class="end"{% endif %}>{{ curr_chapter }}</span>
        </a>
        <ul class="dropdown-list main-bg">
          {% for chapter in all_chapters %}
            <li class="dropdown-element chapter-details"
              {% if chapter == curr_chapter %}data-current="true"{% endif %}>
              <a href="{{ chapter.get_absolute_url }}" title="{{ chapter.title }}"
                 {% if chapter.final %} class="end"{% endif %}>{{ chapter }}</a>
            </li>
          {% endfor %}
        </ul>
      </div>
      {% if config.ALLOW_DLS and request.user.is_authenticated %}
        {% with slug=curr_chapter.series.slug vol=curr_chapter.volume num=curr_chapter.number %}
          <a href="{% url 'reader:cbz' slug vol|default_if_none:0 num %}" id="download"
             title="Download chapter" download><i class="mi mi-download"></i></a>
        {% endwith %}
      {% endif %}
      <div class="dropdown page-list main-bg" aria-haspopup="true">
        <span class="dropdown-title alter-fg">
          Pages <i class="mi mi-down"></i>
        </span>
        <a href="#" rel="nofollow" class="faux-link">
          Page {{ curr_page.number|stringformat:'02d' }}<i class="mi mi-down"></i>
        </a>
        <ul class="dropdown-list main-bg">
          {% for page in all_pages %}
            <li class="dropdown-element page-details"
              {% if page.number == curr_page.number %} data-current="true"{% endif %}>
              {% with num=page.number|stringformat:'02d' %}
                <a href="{{ page.get_absolute_url }}">Page {{ num }}</a>
              {% endwith %}
            </li>
          {% endfor %}
        </ul>
      </div>
    </section>
    <section id="placeholder" class="main-bg"><i class="mi mi-spin"></i></section>
    <img id="page-image" src="{{ curr_page.image.url }}" rel="preload" as="image" alt="Page {{ curr_page.number }}">
    <script src="{% static 'scripts/chapter.js' %}" rel="preload" as="script" type="application/javascript"></script>
    {% with series_url=curr_chapter.series.get_absolute_url prev=curr_page.number|add:-1 next=curr_page.number|add:1 %}
      <section id="controls" class="no-display">
        <div id="controls-top">{# TODO: previous/next chapter instead of first/last page #}
          <a href="{{ all_pages.0.get_absolute_url }}" rel="first"
             title="First page" class="control"><i class="mi mi-rewind"></i></a>
          {% if prev == 0 %}
            {% if prev_chapter %}
              <a href="{{ prev_chapter.get_absolute_url }}" title="Previous chapter" rel="prev" class="control">
            {% else %}
              <a href="{{ series_url }}" title="No previous chapters" rel="prev" class="control">
            {% endif %}
          {% else %}
            <a href="../{{ prev }}/" title="Previous page" rel="prev" class="control">
          {% endif %}
            <i class="mi mi-left"></i>
          </a>
          {% with curr=curr_page.number|stringformat:'02d' max=all_pages|length %}
            <label class="curr-page">
              Page <input type="text" data-max="{{ max }}" value="{{ curr }}"
                          placeholder="{{ curr }}">/{{ max|stringformat:'02d' }}
            </label>
            {% if next > max %}
              {% if next_chapter %}
                <a href="{{ next_chapter.get_absolute_url }}" title="Next chapter" rel="next" class="control">
              {% else %}
                <a href="{{ series_url }}" title="No more chapters" rel="next" class="control">
              {% endif %}
            {% else %}
              <a href="../{{ next }}/" title="Next page" rel="next" class="control">
            {% endif %}
              <i class="mi mi-right"></i>
            </a>
            {% with all_pages|last as last_page %}
              <a href="{{ last_page.get_absolute_url }}" rel="last"
                 title="Last page" class="control"><i class="mi mi-forward"></i></a>
            {% endwith %}
          {% endwith %}
        </div>
      </section>
    {% endwith %}
  </div>
{% endblock %}

reader/templates/directory.html
{% extends 'layout.html' %}
{% load cache custom_tags humanize %}
{% block head_extras %}
  {{ library|jsonld:'library' }}
  <link href="{% url 'library.atom' %}"
        rel="alternate" type="application/atom+xml">
  <link href="{% url 'reader:sitemap.xml' 'series' %}"
        rel="sitemap" type="application/xml" title="Series sitemap">
  <link href="{% url 'reader:sitemap.xml' 'chapters' %}"
        rel="sitemap" type="application/xml" title="Chapters sitemap">
{% endblock %}
{% block title %}
  <meta name="title" content="Series List">
  <meta property="og:title" content="Series List - {{ config.NAME }}">
  <title>Series List &middot; {{ config.NAME }}</title>
{% endblock %}
{% block content %}
  {% cache 600 series_list all_series %}
    <h1 class="text-shadow alter-bg">Series List</h1>
    <article id="list">
      {% for series in all_series %}
        <section class="series">
          <h2 class="series-title">
            <a href="{{ series.get_absolute_url }}" title="{{ series.title }}">
              {{ series.title }}
            </a>
          </h2>
          <div class="cover-container">
            <img src="{{ series.cover.url }}" alt="{{ series }} Cover" class="cover">
          </div>
          <div class="series-info">
            <strong>Latest Chapter{{ config.MAX_CHAPTERS|pluralize }}:</strong>
            {% for chapter in series.chapters.all|vslice:config.MAX_CHAPTERS %}
              <div class="series-chapter">
                <a href="{{ chapter.get_absolute_url }}" title="{{ chapter.title }}"
                   {% if chapter.final %}class="end"{% endif %}>{{ chapter }}</a>
                <div class="chapter-metadata">
                  <span class="divider"></span>
                  {% with groups=chapter.groups.all %}
                    <span class="chapter-groups" title="{{ groups|join:', ' }}">
                      {% for group in groups %}
                        <a href="{{ group.get_absolute_url }}" title="{{ group.name }}"
                           {% if not forloop.last %}class="comma"{% endif %}>{{ group.name }}</a>
                      {% endfor %}
                  {% endwith %}
                  </span>
                  <span class="divider"></span>
                  {% with published=chapter.published %}
                    <time class="chapter-date" title="{{ published|date:'DATETIME_FORMAT' }}"
                          datetime="{{ published|date:'c' }}">{{ published|naturaltime }}</time>
                  {% endwith %}
                </div>
              </div>
            {% endfor %}
          </div>
        </section>
        <span class="alter-bg separator"></span>
      {% endfor %}
    </article>
  {% endcache %}
{% endblock %}
{% block footer %}
  {% include 'footer.html' with rss_url='library.rss' %}
{% endblock %}

reader/templates/series.html
{% extends 'layout.html' %}
{% load static humanize custom_tags %}
{% block head_extras %}
  {% if request.user.is_authenticated %}
    <script src="{% static 'scripts/bookmark.js' %}"
            type="application/javascript" async></script>
  {% endif %}
  {{ book_ld|jsonld:'book-ld' }}
  <link href="{% url 'reader:series.atom' series.slug %}"
        rel="alternate" type="application/atom+xml">
{% endblock %}
{% block keywords %}
  <meta name="keywords" content="{{ tags|join:',' }}">
{% endblock %}
{% block image %}
  <meta name="twitter:card" content="summary">
  {% with cover=PAGE_URL|urljoin:series.cover.url %}
    <meta name="twitter:image" content="{{ cover }}">
    <meta property="og:image" content="{{ cover }}">
    <meta name="twitter:image:alt" content="Series Cover">
    <meta property="og:image:alt" content="Series Cover">
  {% endwith %}
{% endblock %}
{% block description %}
  <meta property="og:description" content="{{ series.description }}">
  <meta name="description" content="{{ series.description }}">
{% endblock %}
{% block title %}
  <meta name="title" content="{{ series.title }}">
  <meta property="og:title" content="{{ series.title }} ~ {{ config.NAME }}">
  <title>{{ series.title }} &middot; {{ config.NAME }}</title>
{% endblock %}
{% block content %}
  <h1 id="series-title" class="text-shadow alter-bg">{{ series.title }}</h1>
  <article id="series">
    <img src="{{ series.cover.url }}" alt="{{ series }} Cover" class="cover">
    {% if user.is_authenticated %}
      <i data-series="{{ series.id }}" data-target="{% url 'user_bookmarks' %}"
         class="bookmark-btn mi mi-bookmark{{ marked|yesno:',-o' }}"
         title="{{ marked|yesno:'Unb,B' }}ookmark"></i>
    {% endif %}
    <div id="series-info">
      {% if aliases %}
        <div id="series-aliases">
          <strong class="alter-fg">Alt. title{{ aliases|pluralize }}:</strong>
          {% for alias in aliases %}<div class="alias">{{ alias }}</div>{% endfor %}
        </div>
      {% endif %}
      {% if authors %}
        <div id="series-authors">
          <strong class="alter-fg">Author{{ authors|pluralize }}:</strong>
          {% for author in authors %}<div class="author">{{ author }}</div>{% endfor %}
        </div>
      {% endif %}
      {% if artists %}
        <div id="series-artists">
          <strong class="alter-fg">Artist{{ artists|pluralize }}:</strong>
          {% for artist in artists %}<div class="artist">{{ artist }}</div>{% endfor %}
        </div>
      {% endif %}
      {% if tags %}
        <div id="series-categories">
          <strong class="alter-fg">Categor{{ tags|pluralize:'y,ies' }}:</strong>
          {% for tag in tags %}<div class="category">{{ tag }}</div>{% endfor %}
        </div>
      {% endif %}
      <div id="series-status">
        <strong class="alter-fg">Status: </strong>
        <span>{{ series.get_status_display }}</span>
      </div>
    </div>
    {% if series.description %}
      <div id="series-desc">
        <h3 class="alter-fg">Description:</h3>
        <div>{{ series.description|linebreaks }}</div>
      </div>
    {% endif %}
    <div id="series-chapters">
      <h3 class="alter-fg">Chapters:</h3>
      {% for chapter in chapters %}
        <div class="chapter">
          <a {% if chapter.final %}class="end"{% endif %}
             href="{{ chapter.get_absolute_url }}"
             title="{{ chapter.title }}">{{ chapter }}</a>
          <div class="chapter-metadata">
            <span class="divider"></span>
            {% with groups=chapter.groups.all %}
              <span class="chapter-groups" title="{{ groups|join:', ' }}">
                {% for group in groups %}
                  <a {% if not forloop.last %}class="comma"{% endif %}
                     href="{{ group.get_absolute_url }}" title="{{ group.name }}">
                    {{ group.name }}</a>
                {% endfor %}
              </span>
            {% endwith %}
            <span class="divider"></span>
            {% with published=chapter.published %}
              <time class="chapter-date" title="{{ published|date:'DATETIME_FORMAT' }}"
                    datetime="{{ published|date:'c' }}">{{ published|naturaltime }}</time>
            {% endwith %}
          </div>
        </div>
      {% empty %}
        <div class="series-licensed">
          This series is licensed. Please read the official release.
        </div>
      {% endfor %}
    </div>
  </article>
{% endblock %}
{% block footer %}
  {% include 'footer.html' with rss_url='reader:series.rss' arg=series.slug %}
{% endblock %}