MangAdventure/urls.py
"""The root URLconf."""

from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.views.decorators.cache import cache_control

from reader import feeds

from .sitemaps import MiscSitemap
from .views import contribute, index, manifest, opensearch, robots, search

_sitemaps = {'sitemaps': {'main': MiscSitemap}}

_sitemap = cache_control(max_age=86400, must_revalidate=True)(sitemap)

#: The main URL patterns.
urlpatterns = [
    path('', index, name='index'),
    path('', include('config.urls')),
    path('search/', search, name='search'),
    path('admin-panel/', admin.site.urls),
    path('reader/', include('reader.urls')),
    path('api/', include('api.urls')),
    path('groups/', include('groups.urls')),
    path('user/', include('users.urls')),
    path('opensearch.xml', opensearch, name='opensearch'),
    path('contribute.json', contribute, name='contribute'),
    path('manifest.webmanifest', manifest, name='manifest'),
    path('robots.txt', robots, name='robots'),
    path('releases.atom', feeds.ReleasesAtom(), name='releases.atom'),
    path('releases.rss', feeds.ReleasesRSS(), name='releases.rss'),
    path('library.atom', feeds.LibraryAtom(), name='library.atom'),
    path('library.rss', feeds.LibraryAtom(), name='library.rss'),
    path('sitemap.xml', _sitemap, _sitemaps, name='sitemap.xml'),
]


#: See :func:`MangAdventure.views.handler400`.
handler400 = 'MangAdventure.views.handler400'

#: See :func:`MangAdventure.views.handler403`.
handler403 = 'MangAdventure.views.handler403'

#: See :func:`MangAdventure.views.handler404`.
handler404 = 'MangAdventure.views.handler404'

#: See :func:`MangAdventure.views.handler500`.
handler500 = 'MangAdventure.views.handler500'

__all__ = [
    'urlpatterns', 'handler400',
    'handler403', 'handler404', 'handler500',
]

api/urls.py
"""The main URLconf of the api app."""

from django.urls import include, path

#: The URL namespace of the API app.
app_name = 'api'

#: The main URL patterns of the API app.
urlpatterns = [
    path('v1/', include('api.v1.urls')),
    path('v2/', include('api.v2.urls')),
]

__all__ = ['urlpatterns']

reader/urls.py
"""The URLconf of the reader app."""

from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from django.urls import path, register_converter
from django.views.decorators.cache import cache_control

from MangAdventure.converters import FloatConverter

from . import feeds, sitemaps, views

register_converter(FloatConverter, 'float')

#: The URL namespace of the reader app.
app_name = 'reader'

_slug = '<slug:slug>/'
_chapter = f'{_slug}<int:vol>/<float:num>/'
_page = f'{_chapter}<int:page>/'

_sitemaps = {
    'template_name': 'image-sitemap.xml',
    'sitemaps': {
        'series': sitemaps.SeriesSitemap,
        'chapters': sitemaps.ChapterSitemap
    }
}

_sitemap = cache_control(max_age=86400, must_revalidate=True)(sitemap)

#: The URL namespace of the reader app.
urlpatterns = [
    path('', views.directory, name='directory'),
    path(_slug, views.series, name='series'),
    path(_chapter, views.chapter_redirect, name='chapter'),
    path(_page, views.chapter_page, name='page'),
    path(f'{_slug[:-1]}.atom', feeds.ReleasesAtom(), name='series.atom'),
    path(f'{_slug[:-1]}.rss', feeds.ReleasesRSS(), name='series.rss'),
    path('<section>-sitemap.xml', _sitemap, _sitemaps, name='sitemap.xml'),
]

if settings.CONFIG['ALLOW_DLS']:
    urlpatterns.append(
        path(f'{_chapter[:-1]}.cbz', views.chapter_download, name='cbz')
    )

__all__ = ['app_name', 'urlpatterns']

MangAdventure/forms.py
"""Custom form fields."""

from django.forms import CharField, URLField

from MangAdventure import validators


class TwitterField(CharField):
    """A :class:`~django.forms.CharField` for Twitter usernames."""
    default_validators = [validators.TwitterNameValidator()]


class DiscordURLField(URLField):
    """A :class:`~django.forms.URLField` for Discord server URLs."""
    default_validators = [validators.DiscordServerValidator()]


__all__ = ['TwitterField', 'DiscordURLField']

MangAdventure/modules/forms.py
from django.core.exceptions import ValidationError
from django.forms import ImageField
from django.utils.six import reraise
from xml.etree import cElementTree as et
from sys import exc_info
from io import BytesIO
from PIL import Image


class SVGImageField(ImageField):

    def to_python(self, data):
        """
        Checks that the file-upload field data contains a
        valid image (GIF, JPG, PNG, possibly others --
        whatever the Python Imaging Library supports).
        """
        test_file = super(ImageField, self).to_python(data)
        if test_file is None:
            return None

        # We need to get a file object for Pillow.
        # We might have a path or we might
        # have to read the data into memory.
        if hasattr(data, 'temporary_file_path'):
            ifile = data.temporary_file_path()
        else:
            if hasattr(data, 'read'):
                ifile = BytesIO(data.read())
            else:
                ifile = BytesIO(data['content'])

        try:
            # load() could spot a truncated JPEG, but it loads the entire
            # image in memory, which is a DoS vector. See #3848 and #18520.
            image = Image.open(ifile)
            # verify() must be called immediately after the constructor.
            image.verify()

            # Annotating so subclasses can reuse it for their own validation
            test_file.image = image
            test_file.content_type = Image.MIME[image.format]
        except OSError:
            # add a workaround to handle svg images
            if not self.is_svg(ifile):
                reraise(ValidationError, ValidationError(
                    self.error_messages['invalid_image'],
                    code='invalid_image',
                ), exc_info()[2])
        if hasattr(test_file, 'seek') and callable(test_file.seek):
            test_file.seek(0)
        return test_file

    def run_validators(self, value):
        if self.is_svg(value):
            return
        super(ImageField, self).run_validators(value)

    @staticmethod
    def is_svg(f):
        """
        Check if provided file is svg
        """
        f.seek(0)
        tag = None
        try:
            for event, el in et.iterparse(f, ('start',)):
                tag = el.tag
                break
        except et.ParseError:
            pass
        return tag == '{http://www.w3.org/2000/svg}svg'


__all__ = ['SVGImageField']

# Source: https://gist.github.com/ambivalentno/9bc42b9a417677d96a21

MangAdventure/views.py
"""The main views and error handlers."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from django.conf import settings
from django.db.models import Prefetch
from django.db.models.functions import Now
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.utils.html import escapejs
from django.views.decorators.cache import cache_control

from groups.models import Group
from reader.models import Category, Chapter

from .bad_bots import BOTS
from .jsonld import breadcrumbs
from .search import parse, query

if TYPE_CHECKING:  # pragma: no cover
    from django.http import HttpRequest


def _error_context(msg: str, status: int = 500) -> dict[str, Any]:
    return {'error_message': msg, 'error_status': status}


@cache_control(public=True, max_age=600, stale_if_error=300)
def index(request: HttpRequest) -> HttpResponse:
    """
    View that serves the index page which shows the latest releases.

    :param request: The original request.

    :return: A response with the rendered ``index.html`` template.
    """
    max_: int = settings.CONFIG['MAX_RELEASES']
    groups = Group.objects.only('name')
    latest = Chapter.objects.filter(
        published__lte=Now(),
        series__licensed=False
    ).order_by('-published').only(
        'title', 'number', 'volume', 'final', 'published',
        'series__title', 'series__slug', 'series__format'
    ).prefetch_related(
        Prefetch('groups', queryset=groups)
    ).select_related('series')[:max_]
    uri = request.build_absolute_uri('/')
    crumbs = breadcrumbs([('Home', uri)])
    return render(request, 'index.html', {
        'breadcrumbs': crumbs,
        'latest_releases': latest
    })


@cache_control(public=True, max_age=600)
def search(request: HttpRequest) -> HttpResponse:
    """
    View that serves a page used for searching for series.

    :param request: The original request.

    :return: A response with the rendered ``search.html`` template.
    """
    results = []
    params = parse(request)
    if request.GET.keys() & {'q', 'author', 'status', 'categories'}:
        results = list(query(params).prefetch_related(
            'categories', 'authors', 'artists'
        ).exclude(licensed=True).order_by('title'))
    uri = request.build_absolute_uri(request.path)
    crumbs = breadcrumbs([('Search', uri)])
    categories = list(Category.objects.all())
    return render(request, 'search.html', {
        'query': params.query,
        'author': params.author,
        'status': params.status,
        'in_categories': params.categories[0],
        'ex_categories': params.categories[1],
        'all_categories': categories,
        'results': results,
        'breadcrumbs': crumbs
    })


@cache_control(public=True, max_age=2628000, immutable=True)
def opensearch(request: HttpRequest) -> HttpResponse:
    """
    View that serves the ``opensearch.xml`` file.

    :param request: The original request.

    :return: A response with the rendered ``opensearch.xml`` template.
    """
    icon = request.build_absolute_uri(settings.CONFIG['FAVICON'])
    search_ = request.build_absolute_uri('/search/')
    self_ = request.build_absolute_uri('/opensearch.xml')
    return render(
        request, 'opensearch.xml', {
            'name': settings.CONFIG['NAME'],
            'icon_type': settings.CONFIG['FAVICON_TYPE'],
            'icon': icon, 'search': search_, 'self': self_,
        }, 'application/opesearchdescription+xml'
    )


@cache_control(public=True, max_age=31536000, immutable=True)
def contribute(request: HttpRequest) -> HttpResponse:
    """
    View that serves the ``contribute.json`` file.

    :param request: The original request.

    :return: A response with the ``contribute.json`` file.
    """
    return render(request, 'contribute.json', {}, 'application/json')


@cache_control(public=True, max_age=2628000, immutable=True)
def manifest(request: HttpRequest) -> HttpResponse:
    """
    View that serves the ``manifest.webmanifest`` file.

    :param request: The original request.

    :return: A response with the ``manifest.webmanifest`` file.
    """
    return render(request, 'manifest.webmanifest', {
        'lang': settings.LANGUAGE_CODE,
        'name': escapejs(settings.CONFIG['NAME']),
        'description': escapejs(settings.CONFIG['DESCRIPTION']),
        'background': settings.CONFIG['MAIN_BG_COLOR'],
        'color': settings.CONFIG['MAIN_TEXT_COLOR'],
    }, 'application/manifest+json')


@cache_control(public=True, max_age=2628000, immutable=True)
def robots(request: HttpRequest) -> HttpResponse:
    """
    View that serves the ``robots.txt`` file.

    :param request: The original request.

    :return: A response with the generated ``robots.txt`` file.
    """
    ctype = 'text/plain; charset=us-ascii'
    robots_ = 'User-agent: *\nDisallow:\n\n' + '\n'.join(
        f'User-agent: {ua}\nDisallow: /\n' for ua in BOTS
    )
    return HttpResponse(content=robots_, content_type=ctype)


def handler400(request: HttpRequest, exception: Exception | None
               = None, template_name: str = 'error.html'
               ) -> HttpResponse:  # pragma: no cover
    """
    Handler for :status:`400` responses.

    :param request: The original request.
    :param exception: The exception that occurred.
    :param template_name: The name of the error template.

    :return: A :class:`~django.http.JsonResponse` for API URLs,
             otherwise a response with the rendered error template.
    """
    if request.path.startswith('/api'):
        return JsonResponse({'error': 'Bad request'}, status=400)
    context = _error_context(
        'The server could not understand the request.', 400
    )
    return render(request, template_name, context, status=400)


def handler403(request: HttpRequest, exception: Exception | None
               = None, template_name: str = 'error.html') -> HttpResponse:
    """
    Handler for :status:`403` responses.

    :param request: The original request.
    :param exception: The exception that occurred.
    :param template_name: The name of the error template.

    :return: A :class:`~django.http.JsonResponse` for API URLs,
             otherwise a response with the rendered error template.
    """
    if request.path.startswith('/api'):  # pragma: no cover
        return JsonResponse({'error': 'Forbidden'}, status=403)
    context = _error_context(
        'You do not have permission to access this page.', 403
    )
    return render(request, template_name, context, status=403)


def handler404(request: HttpRequest, exception: Exception | None
               = None, template_name: str = 'error.html') -> HttpResponse:
    """
    Handler for :status:`404` responses.

    :param request: The original request.
    :param exception: The exception that occurred.
    :param template_name: The name of the error template.

    :return: A :class:`~django.http.JsonResponse` for API URLs,
             otherwise a response with the rendered error template.
    """
    if request.path.startswith('/api'):  # pragma: no cover
        return JsonResponse({'error': 'Invalid API endpoint'}, status=501)
    context = _error_context("Sorry. This page doesn't exist.", 404)
    return render(request, template_name, context, status=404)


def handler500(request: HttpRequest, exception: Exception | None
               = None, template_name: str = 'error.html'
               ) -> HttpResponse:  # pragma: no cover
    """
    Handler for :status:`500` responses.

    :param request: The original request.
    :param exception: The exception that occurred.
    :param template_name: The name of the error template.

    :return: A :class:`~django.http.JsonResponse` for API URLs,
             otherwise a response with the rendered error template.
    """
    if request.path.startswith('/api'):
        return JsonResponse({'error': 'Internal server error'}, status=500)
    context = _error_context(  # Shrug
        'Whoops! Something went wrong. &macr;&#8726;_(&#12484;)_/&macr;'
    )
    return render(request, template_name, context, status=500)


__all__ = [
    'index', 'search', 'opensearch', 'robots',
    'contribute', 'manifest', 'handler400',
    'handler403', 'handler404', 'handler500'
]

MangAdventure/templates/error.html
{% extends 'layout.html' %}
{% block description %}
  <meta property="og:description" content="{{ error_message }}">
  <meta name="description" content="{{ error_message }}">
{% endblock %}
{% block robots %}
  <meta name="robots" content="noindex,nofollow,noarchive">
{% endblock %}
{% block title %}
  <meta property="og:title" content="Error {{ error_status }}">
  <title>Error {{ error_status }} &middot; {{ config.NAME }}</title>
{% endblock %}
{% block content %}
  <h1 class="text-shadow alter-fg">{{ error_message|safe }}</h1>
{% endblock %}

MangAdventure/templates/footer.html
{% load cache %}{% cache 604800 footer rss_url arg token %}
  <footer id="footer">
    <nav id="links">
      <a href="{% url 'info' %}" class="link" title="About us">
        <i class="mi mi-info-circle"></i><span>About us</span>
      </a>
      <a href="{% url 'privacy' %}" class="link" title="Privacy">
        <i class="mi mi-lock"></i><span>Privacy</span>
      </a>
      {% if config.TWITTER %}
        <a href="https://twitter.com/{{ config.TWITTER }}"
           class="link" rel="noopener noreferrer" title="Twitter">
          <i class="mi mi-twitter"></i><span>Twitter</span>
        </a>
      {% endif %}
      {% if config.DISCORD %}
        <a href="{{ config.DISCORD }}" class="link"
           rel="noopener noreferrer" title="Discord">
          <i class="mi mi-discord"></i><span>Discord</span>
        </a>
      {% endif %}
      {% if rss_url %}
        <a {% if arg %}href="{% url rss_url arg %}"
           {% elif token %}href="{% url rss_url %}?token={{ token }}"
           {% else %}href="{% url rss_url %}"{% endif %} class="link"
           rel="alternate" type="application/rss+xml" title="RSS">
          <i class="mi mi-rss"></i><span>RSS</span>
        </a>
      {% endif %}
    </nav>
    {% if config.SHOW_CREDITS %}
      <div id="credits">
        This site was created using
        <a href="https://github.com/mangadventure/MangAdventure"
           rel="noopener" target="_blank">MangAdventure</a>.
      </div>
    {% endif %}
  </footer>
{% endcache %}

MangAdventure/templates/index.html
{% extends 'layout.html' %}
{% load cache humanize custom_tags %}
{% block head_extras %}
  <link href="{% url 'sitemap.xml' %}" rel="sitemap"
        type="application/xml" title="Main sitemap">
{% endblock %}
{% block title %}
  <meta name="title" content="Latest Releases">
  <meta property="og:title" content="Home - {{ config.NAME }}">
  <title>Home &middot; {{ config.NAME }}</title>
{% endblock %}
{% block content %}
  {% cache 600 releases latest_releases %}
    <h1 class="text-shadow alter-bg">Latest Releases</h1>
    <article id="latest">
      {% for release in latest_releases %}
        <section class="release">
          <h2 class="release-title">
            <a href="{{ release.series.get_absolute_url }}" title="{{ release.series }}">
              {{ release.series }}
            </a>
          </h2>
          <div class="release-info">
            <a href="{{ release.get_absolute_url }}" title="{{ release.title }}"
               class="release-link{% if release.final %} end{% endif %}">{{ release }}</a>
            <div class="chapter-metadata">
              <span class="divider"></span>
              {% with groups=release.groups.all  %}
                <span class="chapter-groups" title="{{ groups|join:', ' }}">
                  {% for group in groups %}
                    <a href="{{ group.get_absolute_url }}" title="{{ group.name }}"
                       {% if not forloop.last %}class="comma"{% endif %}>
                      {{ group.name }}
                    </a>
                  {% endfor %}
              {% endwith %}
              </span>
              <span class="divider"></span>
              {% with published=release.published %}
                <time class="chapter-date" title="{{ published|date:'DATETIME_FORMAT' }}"
                      datetime="{{ published|date:'c' }}">{{ published|naturaltime }}</time>
              {% endwith %}
            </div>
          </div>
        </section>
      {% endfor %}
    </article>
  {% endcache %}
{% endblock %}
{% block footer %}
  {% include 'footer.html' with rss_url='releases.rss' %}
{% endblock %}

MangAdventure/templates/layout.html
<!DOCTYPE html>{% load cache static custom_tags %}
<html lang="en-us">{% spaceless %}
  <head>
    {% cache 604800 meta %}
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta name="generator" content="MangAdventure v{{ MANGADV_VERSION }}">
      <meta name="license" content="MIT">
    {% endcache %}
    {% block color %}
      <meta name="theme-color" content="{{ config.ALTER_BG_COLOR }}">
      <meta name="msapplication-navbutton-color" content="{{ config.ALTER_BG_COLOR }}">
      <meta name="apple-mobile-web-app-status-bar-style" content="{{ config.ALTER_BG_COLOR }}">
    {% endblock %}
    {% block keywords %}
      <meta name="keywords" content="{{ config.KEYWORDS }}">
    {% endblock %}
    {% block robots %}
      <meta name="robots" content="index,follow">
    {% endblock %}
    {% block description %}
      <meta property="og:description" content="{{ config.DESCRIPTION }}">
      <meta name="description" content="{{ config.DESCRIPTION }}">
    {% endblock %}
    {% block image %}
      <meta name="twitter:card" content="summary_large_image">
      <meta name="twitter:image" content="{{ PAGE_URL|urljoin:config.LOGO_TW }}">
      <meta property="og:image" content="{{ PAGE_URL|urljoin:config.LOGO_OG }}">
      <meta name="twitter:image:alt" content="Site logo">
      <meta property="og:image:alt" content="Site logo">
    {% endblock %}
    {% block url %}
      <meta name="url" content="{{ PAGE_URL }}">
      <meta property="og:url" content="{{ PAGE_URL }}">
    {% endblock %}
    {% cache 604800 links %}
      {% if config.DISCORD %}
        <meta name="discord" content="{{ config.DISCORD }}">
      {% endif %}
      {% if config.TWITTER %}
        <meta name="twitter:site" content="@{{ config.TWITTER }}">
      {% endif %}
      <meta name="twitter:site_name" content="{{ config.NAME }}">
      <meta property="og:determiner" content="">
      <meta property="og:type" content="website">
      <meta property="og:site_name" content="{{ config.NAME }}">
      <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
      <link href="{{ config.FAVICON }}" rel="shortcut icon" type="{{ config.FAVICON_TYPE }}">
      <link href="{% url 'manifest' %}" rel="manifest" type="application/manifest+json">
      <link href="{% url 'opensearch' %}" rel="search" title="{{ config.NAME }}"
            type="application/opensearchdescription+xml">
      <link href="https://cdn.statically.io/gh/mangadventure/font/962fc56/dist/mangadventure.css"
            integrity="sha384-E9mWT8anu+llDRZWGNe7f60aZ8ZX3BWK6vmL8O2tg6nhZN1XuDwGdf71seCrjnjr"
            rel="stylesheet" type="text/css" crossorigin="anonymous">
      <link href="{{ config.FONT_URL }}" rel="stylesheet" type="text/css" crossorigin="anonymous">
    {% endcache %}
    {% block canonical %}
      <link href="{{ CANON_URL }}" rel="canonical" type="text/html">
    {% endblock %}
    {% block stylesheets %}
      {% cache 604800 styles %}
        <link href="{% static 'styles/style.scss' %}"
              rel="stylesheet preload" as="style" type="text/css">
        <link href="{% static 'styles/extra.scss' %}" rel="stylesheet" type="text/css">
        <noscript>
          <link href="{% static 'styles/noscript.css' %}" rel="stylesheet" type="text/css">
        </noscript>
      {% endcache %}
    {% endblock %}
    {% if config.UMAMI_ID and config.UMAMI_URL %}
      <script data-website-id="{{ config.UMAMI_ID }}" data-host-url="{{ config.UMAMI_URL }}" data-do-not-track="true"
              type="application/javascript" src="{% static 'vendor/umami.js' %}" async></script>
    {% endif %}
    {% block head_extras %}{% endblock %}
    {{ searchbox|jsonld:'website' }}
    {{ organization|jsonld:'organization' }}
    {% block breadcrumbs %}
      {{ breadcrumbs|jsonld:'breadcrumbs' }}
    {% endblock %}
    {% block title %}
      <meta property="og:title" content="{{ config.NAME }}">
      <meta name="title" content="{{ config.NAME }}">
      <title>{{ config.NAME }}</title>
    {% endblock %}
  </head>
  <body>
    <header id="header">
      {% cache 604800 logo %}
        <a id="home" href="{% url 'index' %}">
          <img id="logo" alt="Logo" src="{{ config.LOGO }}">
        </a>
      {% endcache %}
      <nav id="navig">
        <ul class="navig-list">
          {% cache 604800 nav %}
            <li>
              <a class="navig-link" href="{% url 'index' %}">
                <i class="mi mi-clock"></i><span class="ident">Latest</span>
              </a>
            </li>
            <li>
              <a class="navig-link" href="{% url 'reader:directory' %}">
                <i class="mi mi-library"></i><span class="ident">Library</span>
              </a>
            </li>
            <li id="searchlink">
              <a class="navig-link" href="{% url 'search' %}">
                <i class="mi mi-search"></i><span class="ident">Search</span>
              </a>
            </li>
            <li>
              <form action="{% url 'search' %}" method="GET">
                <input placeholder="Type a series to search for"
                       name="q" type="search" class="main-bg" id="searchbox">
              </form>
            </li>
          {% endcache %}
          <li class="dropdown" aria-haspopup="true">
            <span class="navig-link dropdown-title" aria-label="User">
              <i class="mi mi-user" aria-hidden="true"></i>
            </span>
            <ul class="dropdown-list">{% if request.user.is_authenticated %}
              <li class="dropdown-element">
                <a href="{% url 'user_profile' %}?id={{ request.user.id }}" rel="nofollow">
                  <span>Profile</span><i class="mi mi-user" aria-hidden="true"></i>
                </a>
              </li>
              <li class="dropdown-element">
                <a href="{% url 'user_bookmarks' %}" rel="nofollow">
                  <span>Bookmarks</span><i class="mi mi-bookmark" aria-hidden="true"></i>
                </a>
              </li>
              <li class="dropdown-element">
                <a href="{% url 'user_edit' %}" rel="nofollow">
                  <span>Settings</span><i class="mi mi-cog" aria-hidden="true"></i>
                </a>
              </li>
              <li class="dropdown-element">
                <form action="{% url 'account_logout' %}" method="POST">
                  <input type="hidden" name="next" value="{{ request.path }}">
                  <button type="submit" class="logout-btn">
                    <span>Logout</span><i class="mi mi-logout" aria-hidden="true"></i>
                  </button>
                </form>
              </li>
            {% else %}
              <li class="dropdown-element">
                <a href="{% url 'account_login' %}?next={{ request.path }}" rel="nofollow">
                  <span>Login</span><i class="mi mi-login" aria-hidden="true"></i>
                </a>
              </li>
            {% endif %}</ul>
          </li>
        </ul>
      </nav>
    </header>
    {% if messages %}
      <aside id="messages">
        {% for message in messages %}
          <div class="message {{ message.tags }}">{{ message }}</div>
        {% endfor %}
      </aside>
    {% endif %}
    <main id="content">
      {% block content %}
      {% endblock %}
    </main>
    {% block footer %}{% include 'footer.html' %}{% endblock %}
  </body>
</html>{% endspaceless %}